const ORDER_STATUSES = {
  PLACED: "PLACED",
  IN_PROGRESS: "IN_PROGRESS",
  READY: "READY",
  SERVED: "SERVED",
  CANCELLED: "CANCELLED",
};

const ACTIVE_ORDER_STATUSES = [
  ORDER_STATUSES.PLACED,
  ORDER_STATUSES.IN_PROGRESS,
  ORDER_STATUSES.READY,
];

module.exports = { ORDER_STATUSES, ACTIVE_ORDER_STATUSES };
