const ROLES = {
  OWNER: "OWNER",
  MANAGER: "MANAGER",
  KITCHEN: "KITCHEN",
  WAITER: "WAITER",
};

const STAFF_ROLES = [ROLES.MANAGER, ROLES.KITCHEN, ROLES.WAITER];

module.exports = { ROLES, STAFF_ROLES };
